# Definition for CI within GitLab
# Note:
#    Prefix any job name with a '.' to disable.
#


# Enable submodules
variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none


# Common definitions for the jobs
.common: &common
  before_script:
    - git submodule sync ci
    - git submodule update --init ci
  artifacts:
    when: always
    paths:
      - artifacts
      - ci-logs
  dependencies: []


#### Builds ####
build-command-riscos:
  <<: *common
  stage: build
  script:
    - ci/build.sh install


#### Stages to execute ####
stages:
  - build
